import { VerticalBox, HorizontalBox } from "std-widgets.slint";
import { IconButton } from "./button.slint";
import "./assets/fonts/Roboto-Regular.ttf";


export component MainWindow inherits Window {
    title: "Pomodoro Timer";
    width: 340px;
    height: 240px;
    background: #2d2d2d;
    icon: @image-url("./assets/icons/app.svg");
    default-font-family: "Roboto";

    in-out property <int> remaining_seconds: 25 * 60;
    in-out property <bool> timer_active: false;
    in-out property <string> current_state_text: "Work";

    callback start_pause_clicked();
    callback reset_clicked();
    callback skip_clicked();

    VerticalBox {
        spacing: 10px;
        padding: 10px;
            
        Rectangle {
            width: 100%;
            height: 50px;
            background: #424242;
            border-radius: 20px;
            border-width: 1px;
            border-color: #333333;

            Text {
                text: root.current_state_text;
                horizontal-alignment: center;
                font-size: 24px;
                color: #fefefe;
            }
        }

        Text {
            text: 
                Math.floor(root.remaining_seconds / 60) + ":" 
                + (Math.mod(root.remaining_seconds, 60) < 10 ? "0" : "") 
                + Math.mod(root.remaining_seconds, 60);
            horizontal-alignment: center;
            font-size: 50px;
            font-weight: 700;
            color: #fefefe;
        }

        HorizontalBox {
            alignment: center;
            spacing: 10px;

            IconButton {
                icon: 
                    root.timer_active 
                    ? @image-url("./assets/icons/pause.svg") 
                    : @image-url("./assets/icons/play.svg");
                background_default: #e54f4f;
                background_pressed: #e28f8f;
                background_hover: #e86e6e;
                clicked => { root.start_pause_clicked() }
            }

            IconButton {
                icon: @image-url("./assets/icons/reset.svg");
                background_default: #4fabf6;
                background_pressed: #91c7f4;
                background_hover: #72bcf9;
                clicked => { root.reset_clicked() }
            }

            IconButton {
                icon: @image-url("./assets/icons/skip.svg");
                background_default: #4fc055;
                background_pressed: #9ac99c;
                background_hover: #74c678;
                clicked => { root.skip_clicked() }
            }
        }
    }
}
